# Generated by Django 2.2 on 2019-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
