# Generated by Django 2.2 on 2019-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190410_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
